//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbDataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Delivery()
        {
            this.Shops = new HashSet<Shop>();
        }
    
        public string MerchType { get; set; }
        public int Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop> Shops { get; set; }

        public static implicit operator DbEssense.Delivery(Delivery v)
        {
            DbEssense.Delivery delivery = new DbEssense.Delivery();
            delivery.Id = v.Id;
            delivery.Shop = (ICollection<DbEssense.Shop>)v.Shops;
            delivery.MerchType = v.MerchType;
            return delivery;
        }
    }
}
