//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbDataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group()
        {
            this.Shops = new HashSet<Shop>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string MainAlbum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop> Shops { get; set; }

        public static implicit operator DbEssense.Group(Group v)
        {
            DbEssense.Group group = new DbEssense.Group();
            group.Shop = (ICollection<DbEssense.Shop>)v.Shops;
            group.Name = v.Name;
            group.MainAlbum = v.MainAlbum;
            group.Id = v.Id;
            return group;
        }
    }
}
