//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbDataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public int Id { get; set; }
        public int GroupId { get; set; }
        public int LocationId { get; set; }
        public int EmployeId { get; set; }
        public int DeliveryManId { get; set; }
        public string Name { get; set; }
    
        public virtual Delivery Delivery { get; set; }
        public virtual Employe Employe { get; set; }
        public virtual Group Group { get; set; }
        public virtual Location Location { get; set; }

        public static implicit operator DbEssense.Shop(Shop v)
        {
            DbEssense.Shop shop = new DbEssense.Shop();
            shop.DeliveryManId = v.DeliveryManId;
            shop.GroupId = v.GroupId;
            shop.EmployeId = v.EmployeId;
            shop.LocationId = v.LocationId;
            shop.Name = v.Name;
            shop.Id = v.Id;
            return shop;
        }
    }
}
